import turtle

w = turtle.Screen()
w.title('tortuga')
andres = turtle.Turtle()
andres.speed(2)
andres.shape ('turtle')
andres.begin_fill()
andres.setposition(0,0)
for i in range(4):
    andres.forward(50)
    andres.right(90)
andres.end_fill()

andres.penup()
andres.setposition(30,50)
andres.pendown()
andres.color('blue')
andres.pensize (4)
andres.begin_fill()
andres.left(45)
andres.forward(50)
andres.left(90) 
andres.forward(50)
andres.left(90) 
andres.forward(50)
andres.left(90) 
andres.forward(50)
andres.left(90)
andres.end_fill()

andres.penup()
andres.setposition(10,150)
andres.pendown()
andres.begin_fill()
andres.color('red')
andres.pensize (1)
andres.right(45)
andres.forward(50)
andres.left(72)
andres.forward(50)
andres.left(72) 
andres.forward(50)
andres.left(72) 
andres.forward(50)
andres.left(72) 
andres.forward(50)
andres.left(72) 
andres.end_fill()

andres.penup()
andres.setposition(-150,-100)
andres.pendown()
andres.color('green')
andres.begin_fill()
andres.forward(100)
andres.left(90)
andres.forward(50)
andres.left(90) 
andres.forward(100)
andres.left(90) 
andres.forward(50)
andres.end_fill()
turtle.mainloop()